global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'

rule_files:
  - '/etc/prometheus/rules/myrule.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/prometheus/metrics'

  - job_name: 'node resources'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'node-exporter:9100'
        labels:
          group: 'Monitor_Server'

  # https://flower.readthedocs.io/en/latest/prometheus-integration.html#configure-and-start-prometheus      
  - job_name: flower
    scrape_interval: 30s
    static_configs:
    - targets: ['172.20.0.5:5555']
    # basic_auth:
    #   username: ''
    #   password: ''

  - job_name: 'blackbox'
    metrics_path: 'blackbox/probe'
    scrape_interval: 30s
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - 'http://prometheus.io'
        - 'https://prometheus.io'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.

  - job_name: cadvisor
    scrape_interval: 30s
    static_configs:
    - targets:
      - 'cadvisor:8080'
      labels:
        group: 'Monitor_Server'
    metrics_path: '/cadvisor/metrics'

  # - job_name: postgres-exporter
  #   scrape_interval: 1m
  #   static_configs:
  #   - targets: ['']

  # - job_name: mongodb-exporter
  #   scrape_interval: 1m
  #   static_configs:
  #   - targets: ['']

  - job_name: process-exporter
    scrape_interval: 10s
    static_configs:
    - targets: 
      - 'process-exporter:9256'
      labels:
        group: 'Monitor_Server'
      
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['altermanager:9093']