version: '3.3'
services:
  elasticsearch:
    build:
      context: ./
      dockerfile: Dockerfile-elasticsearch
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION:-7.16.1}
    init: true
    container_name: es
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    environment:
      xpack.security.enabled: "true"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      ELASTIC_PASSWORD_FILE: /run/secrets/es_password
    deploy:
      resources:
        limits:
          cpus: ${ELASTIC_CPU:-1.0}
          memory: ${ELASTIC_MEM:-2.0G}
    networks: 
      - elastic
    secrets:
      - es_password

  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION:-7.16.1}
    container_name: kibana
    ports:
      - "5601:5601"
    networks: 
      - elastic
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch

volumes:
  esdata01:

secrets:
  es_password:
    file: ./es_password.txt

networks: 
  elastic: 