version: '3.7'
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: jenkins_cadvisor
    ports:
      - 8000:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
    networks:
      jenkins:
  

  jenkins:
    build: .
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins_master
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
    networks:
      jenkins:

volumes:
  jenkins_data:

networks:
  jenkins:
