version: '3.7'
services:

  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
    privileged: true
    init: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins_master
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      jenkins:


volumes:
  jenkins_data:

networks:
  jenkins: